### ISSUE TITLE
Maybe users should be able to click the extension icon to toggle reading mode?

### ISSUE THREAD

**Issue by v** [StephenAlanBuckley/Confluent#1]
The first time I opened this up, I went to confluence and tried to click on the extension icon, because I didn't notice the new "Read" button in confluence.

Since clicking the icon doesn't do anything, I think this is a reasonable suggestion.

**Comment by StephenAlanBuckley** [comment]
Makes sense! I'll see what I can do :)

**Comment by StephenAlanBuckley** [comment]
Alrighty- latest version of the code now has this!

Thanks a lot- this is a great suggestion and was fun to figure out!
